

services:
  backend:
    build: ./backend
    container_name: flask-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_DEBUG=1
      - PYTHONPATH=/app

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    depends_on:
      - backend
